# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Keyfactor Integrations Catalog **DRAFT**
description: >- # this means to ignore newlines until "baseurl:"
  A collection of Keyfactor integrations to help you quickly get started with integrating 
  the platform with your enterprise services.  The catalog is organized by integration type, 
  and for each integration we've provided the source code as well as pre-compiled binary files.

# baseurl: "/keyfactor-integrations" # the subpath of your site, e.g. /blog
url: "https://keyfactor.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# collections:
#   integrations:
#     output: true
#     permalink: /integrations/:name

mathjax: # this will prased to json, default: {}

mermaid:
  custom:     # mermaid link
  initialize: # this will prased to json, default: {}

scss:   # also _includes/extra/styles.scss
script: # also _includes/extra/script.js

# Build settings
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true  


plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
